Repository cloudposse/terraform-aws-sns-lambda-notify-slack, pull requests merged in 2024-07, with the labels that each got.

#60 fix: add an attribute to examples/completed to avoid name conflict in test concurrent runs
  README.md
  docs/terraform.md
  examples/complete/main.tf
  examples/complete/versions.tf
  main.tf
  versions.tf
Labels: triage

#61 Fix release workflow
  .github/workflows/release.yml
  examples/complete/main.tf
  test/src/examples_complete_test.go
Labels: needs-cloudposse

#62 Update .github/settings.yml
  .github/auto-release.yml
  .github/settings.yml
Labels: auto-update, no-release, migration
